-- Wszystkie trzy zadania mają znaleźć się w tym pliku
-- 1. typ Tree
-- 2. Implementacja Functora dla drzewa
-- 3. Implementacja Monady dla drzewa
-- 4. Operacje na drzewie jako stateful computations
-- 5. Przykładowe użycie drzewa w notacji 'do'.